language: node_js
node_js:
  - "4.0"
  - "5.0"
before_install:
  - npm install -g npm@latest
  - npm install -g greenkeeper-lockfile@1

before_script: greenkeeper-lockfile-update

after_script: greenkeeper-lockfile-upload

install:
  - npm install
  - npm install -g codecov

script:
- npm run lint
- npm run test
- codecov
